version: '3.8'
services:
    web:
        build:
            context: ./tradingbot_web
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db