version: '3.8'
services:
    certbot:
        image: certbot/certbot
        restart: always
        depends_on:
            - nginx
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 720h & wait $${!}; done;'"
    nginx:
        image: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db
    web:
        restart: always
        depends_on:
            - db
        build:
            context: ./tradingbot_web
        ports:
            - "3000:3000"