version: '3.8'
services:
    certbot:
        image: certbot/certbot
        restart: always
        depends_on:
            - nginx
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 720h & wait $${!}; done;'"
    nginx:
        image: nginx
        restart: always
        depends_on:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    web:
        restart: always
        depends_on:
            - db
        environment:
            - DB_USERNAME=dbuser
            - DB_PASSWORD=dbpassword
            - DB_NAME=tradingbot_db
            - SERVER_ROOT_URI=https://tradingbot.ahsien.rocks
        build:
            context: ./tradingbot_web
        ports:
            - "3000:3000"
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=dbuser
            - MONGO_INITDB_ROOT_PASSWORD=dbpassword
            - MONGO_INITDB_DATABASE=tradingbot_db
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db